config/routes.rb
Rails.application.routes.draw do

  resources :workouts do 
    resources :exercises
  end
  root 'workouts#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :mood, :workout, :date, presence: true
  has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :find_exercise, only: [:update, :edit]

  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))
    redirect_to workout_path(@workout)
  end

  def edit
  end

  def update
    @exercise.update_attributes(exercise_params) 
    redirect_to workout_path(@workout)
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name,:sets,:reps)
  end

  def find_exercise
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  before_action :find_workout, only: [:show, :update, :edit, :destroy]  

  def index
    @workouts = Workout.all.order('created_at DESC')
  end

  def show

  end

  def new 
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else 
      render 'new'
    end
  end

  def edit

  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else 
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :mood, :length, :workout)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps
%div= link_to "EDIT", edit_workout_exercise_path(@workout, exercise)

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|
  = f.input :name
  = f.input :sets
  = f.input :reps
  = f.button :submit

app/views/exercises/edit.html.haml
= simple_form_for([@workout, @exercise]) do |f|
  = f.input :name
  = f.input :sets
  = f.input :reps
  = f.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p>
    Hi
  </p>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WorkoutLog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#{root_path}"} FitLife
        #navbar.navbar-collapse.collapse
          %form.navbar-form.navbar-right
            .form-group
              %input.form-control{:placeholder => "Email", :type => "text"}/
            .form-group
              %input.form-control{:placeholder => "Password", :type => "password"}/
            %button.btn.btn-success{:type => "submit"} Sign in
        / /.navbar-collapse
    / Main jumbotron for a primary marketing message or call to action
    .container
      = yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
          %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more »
  = f.input :date, label: "Date"
  = f.input :workout, label: "Workout", input_html: { class: "form-control" }
  = f.input :mood, label: "Mood", input_html: { class: "form-control" }
  = f.input :length, label: "Length", input_html: { class: "form-control" }
  = f.submit :submit

app/views/workouts/edit.html.haml
= render 'form'

app/views/workouts/index.html.haml
%h1 Hello, World!

= link_to "NEW WORKOUT", new_workout_path


- @workouts.each do |w|
  %h2= w.date
  %h3= w.workout 
  %p= link_to w.mood, w

app/views/workouts/new.html.haml
= render 'form'

app/views/workouts/show.html.haml
#workout
  %p= @workout.date
  %p= @workout.mood
  %p= @workout.workout
  %p= @workout.length
  %div= link_to "EDIT", edit_workout_path(@workout)
  %div= link_to "DELETE", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" }

#exercises
  = render @workout.exercises
  = render "exercises/form"